### ISSUE TITLE
28 pull requests had merge conflicts and were not merged

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/discovery-artifact-manager#1267]
From [December 14](https://github.com/googleapis/discovery-artifact-manager/pull/737) until [January 27](https://github.com/googleapis/discovery-artifact-manager/pull/1020), 28 automatically generated discovery document updates could not be merged due to merge conflicts.

During the same period, hundreds of pull requests were successfully merged because they contained no conflicts, for example [#828](https://github.com/googleapis/discovery-artifact-manager/pull/828).

When I click on the merge button, the [conflicts are so large and complex](https://github.com/googleapis/discovery-artifact-manager/pull/883/conflicts) I have no hope of resolving them.

I ask for help for the original authors of this code:
@saicheems @andreamlin @vchudnov-g @tcoffee-google 

Why did the generated code conflict?

**Comment by vchudnov-g** [comment]
I don't know why the conflicts appeared and then went away (eg admob was in the reported conflict you listed, but it has been successfully auto-merged since). I'd be somewhat curious to learn.

That said, do you need these mirrored Discoveries for anything? Originally we set them up for Apiary-library samplegen, but since we're moving to a simpler maintenance model that involves not auto-generating samples, we won't need to update them any more. Do you use them for something else?

**Comment by JustinBeckwith** [comment]
Would it be harmful to close the current batch of unresolved PRs?  Would they just get sent again?

**Comment by vchudnov-g** [comment]
It probably wouldn't be harmful, but they may well get regenerated. If you folks don't need the up-to-date Discoveries, we should find the job that does the generation and cancel it.

**Comment by SurferJeffAtGoogle** [comment]
I think we can close them, without harm, and they won't be regenerated.

**Comment by SurferJeffAtGoogle** [comment]
I see Justin closed all 28 PRs yesterday.
